Fix/play nice with other middleware
expert360/absinthe_auth pull request #10
Opened 2018-11-12 21:18 UTC by justanotherdot

This checks for the Absinthe.Resolution or default middleware in order
to jam back in the default if it has been stripped. We do not want to
insert the default middleware, however, if we have a function being used
for resolution for a field.

The commit prior to the fix demonstrates the failure. 

If you checkout this PR locally:

```
git checkout HEAD^1
mix deps.get
mix compile
mix test test/absinthe_auth_test.exs:57
```

The test should fail as the default middleware has been stripped
and it isn't being properly replaced by `absinthe_auth`.

This patches up the hole on our end, but it would be nice to know
upstream why this isn't happening. I am going to try to open an upstream
issue to discuss when I find the time. I will link back to this PR when I do.

2018-11-12 22:49 UTC, coderdan requested changes

2018-11-12 22:49 UTC, coderdan commented on lib/absinthe_auth/middleware.ex
> +      mware_mod == Absinthe.Middleware.MapGet ||
Perhaps this could be easier to read with something like:
```elixir
mware_mod in [Absinthe.Middleware.MapGet, Absinthe.Resolution]
```

2018-11-12 22:49 UTC, coderdan commented on lib/absinthe_auth/middleware.ex
> +    if Enum.empty?(resolution.middleware) && has_no_resolution_mware? do
Do you need to check both of these? The former may be true but have no resolution middleware. So what if there is a non-resolving middleware set but no resolution middleware? The result would be no resolution set.

2018-11-13 01:30 UTC, justanotherdot commented
I've rebased with some refactoring: 

* Was doing de morgan's law in my head but wasn't considering short-circuit logic so I borked the result
* `has_no_resolution_mware?` is actually wrong because it is two tuples with a two-tuple in the first position, not just a two-tuple.

2018-11-13 04:55 UTC, coderdan approved these changes

2018-11-13 04:57 UTC, merged